"""Cost model for e-graph extraction.

FLOPs-based cost model that estimates compute cost from operator type
and tensor shapes.  Falls back to profiled per-op average latency when
shape information is unavailable.
"""

from __future__ import annotations

import json
from pathlib import Path

from ..egraph.enode import ENode
from ..ir.node import OP_INPUT, OP_NOOP, OP_PROJ, OP_WEIGHT

# Ops that are structural/boundary — zero cost.
_FREE_OPS = frozenset({
    OP_INPUT, OP_WEIGHT, OP_NOOP, OP_PROJ,
    "Constant", "ConstantOfShape",
})

# Ops that are essentially memory moves — cost proportional to numel
# but much cheaper than compute ops.
_MEMORY_OPS = frozenset({
    "Reshape", "Transpose", "Squeeze", "Unsqueeze", "Flatten",
    "Expand", "Gather", "Concat", "Split", "Slice", "Pad",
    "Identity", "Cast",
})

# Element-wise ops — cost proportional to numel.
_ELEMENTWISE_OPS = frozenset({
    "Add", "Sub", "Mul", "Div", "Pow", "Sqrt", "Reciprocal", "Neg",
    "Relu", "Sigmoid", "Tanh", "Clip", "LeakyRelu", "Elu", "Selu",
    "Where", "Min", "Max", "Abs", "Ceil", "Floor", "Log", "Exp",
    "Erf", "Gelu", "Equal", "Less", "Greater", "LessOrEqual",
    "GreaterOrEqual", "Not", "And", "Or",
})

# Default cost table path (generated by profile_ops.py).
_DEFAULT_COST_TABLE = Path(__file__).resolve().parent.parent.parent.parent / (
    "artifacts/superopt/op_cost_table.json"
)


def _numel(shape: tuple[int, ...] | None) -> int | None:
    """Product of shape dimensions, or None if shape is unknown/dynamic."""
    if shape is None:
        return None
    n = 1
    for d in shape:
        if d < 0:
            return None
        n *= d
    return n


def _flops_matmul(
    output_shape: tuple[int, ...] | None,
    input_shapes: list[tuple[int, ...] | None] | None,
) -> float | None:
    """FLOPs for MatMul: 2*M*K*N per batch element."""
    if input_shapes and len(input_shapes) >= 2:
        a_shape = input_shapes[0]
        b_shape = input_shapes[1]
        if a_shape and b_shape and len(a_shape) >= 2 and len(b_shape) >= 2:
            M, K = a_shape[-2], a_shape[-1]
            N = b_shape[-1]
            if M > 0 and K > 0 and N > 0:
                batch = 1
                for d in a_shape[:-2]:
                    if d < 0:
                        return None
                    batch *= d
                return 2.0 * batch * M * K * N
    return None


def _flops_conv(
    output_shape: tuple[int, ...] | None,
    input_shapes: list[tuple[int, ...] | None] | None,
    attrs: tuple[tuple[str, object], ...],
) -> float | None:
    """FLOPs for Conv: 2 * N * Cout * spatial_out * Cin/g * kernel_spatial."""
    attrs_dict = dict(attrs)
    kernel_shape = attrs_dict.get("kernel_shape")
    group = attrs_dict.get("group", 1)
    if not isinstance(group, int):
        group = 1

    if input_shapes and len(input_shapes) >= 1 and input_shapes[0]:
        c_in = input_shapes[0][1] if len(input_shapes[0]) >= 2 else None
    else:
        c_in = None

    if output_shape and len(output_shape) >= 2:
        n_batch = output_shape[0] if output_shape[0] > 0 else 1
        c_out = output_shape[1]
        spatial_out = 1
        for d in output_shape[2:]:
            if d < 0:
                return None
            spatial_out *= d
    else:
        return None

    if kernel_shape and c_in and c_in > 0 and c_out > 0:
        kernel_spatial = 1
        for k in kernel_shape:
            kernel_spatial *= k
        return 2.0 * n_batch * c_out * spatial_out * (c_in // group) * kernel_spatial

    return None


def _flops_gemm(
    input_shapes: list[tuple[int, ...] | None] | None,
    attrs: tuple[tuple[str, object], ...],
) -> float | None:
    """FLOPs for Gemm: 2*M*K*N (+ M*N for bias)."""
    if not input_shapes or len(input_shapes) < 2:
        return None
    a_shape = input_shapes[0]
    b_shape = input_shapes[1]
    if not a_shape or not b_shape:
        return None
    attrs_dict = dict(attrs)
    trans_a = attrs_dict.get("transA", 0)
    trans_b = attrs_dict.get("transB", 0)
    if len(a_shape) == 2 and len(b_shape) == 2:
        M = a_shape[1] if trans_a else a_shape[0]
        K = a_shape[0] if trans_a else a_shape[1]
        N = b_shape[0] if trans_b else b_shape[1]
        if M > 0 and K > 0 and N > 0:
            return 2.0 * M * K * N
    return None


def _flops_reduce(
    input_shapes: list[tuple[int, ...] | None] | None,
) -> float | None:
    """FLOPs for reduction ops: proportional to input numel."""
    if input_shapes and input_shapes[0]:
        n = _numel(input_shapes[0])
        if n is not None:
            return float(n)
    return None


def _flops_softmax(
    output_shape: tuple[int, ...] | None,
) -> float | None:
    """FLOPs for Softmax: ~5*numel (exp, sum, div, max, sub)."""
    n = _numel(output_shape)
    if n is not None:
        return 5.0 * n
    return None


def _flops_norm(
    input_shapes: list[tuple[int, ...] | None] | None,
) -> float | None:
    """FLOPs for normalization ops (LayerNorm, BatchNorm, etc.)."""
    if input_shapes and input_shapes[0]:
        n = _numel(input_shapes[0])
        if n is not None:
            return 5.0 * n
    return None


def estimate_flops(
    op: str,
    output_shape: tuple[int, ...] | None = None,
    input_shapes: list[tuple[int, ...] | None] | None = None,
    attrs: tuple[tuple[str, object], ...] = (),
) -> float | None:
    """Estimate FLOPs for a single op.  Returns None if not estimable."""
    if op in _FREE_OPS:
        return 0.0

    if op in _MEMORY_OPS:
        n = _numel(output_shape)
        return float(n) * 0.1 if n is not None else None

    if op in _ELEMENTWISE_OPS:
        n = _numel(output_shape)
        return float(n) if n is not None else None

    if op == "MatMul":
        return _flops_matmul(output_shape, input_shapes)
    if op == "Conv":
        return _flops_conv(output_shape, input_shapes, attrs)
    if op == "Gemm":
        return _flops_gemm(input_shapes, attrs)
    if op == "Softmax":
        return _flops_softmax(output_shape)
    if op in ("ReduceMean", "ReduceSum", "ReduceMax", "ReduceMin",
              "ReduceProd", "ReduceL2"):
        return _flops_reduce(input_shapes)
    if op in ("LayerNormalization", "BatchNormalization",
              "InstanceNormalization", "GroupNormalization"):
        return _flops_norm(input_shapes)

    # Unknown op: try numel as rough proxy.
    n = _numel(output_shape)
    if n is not None:
        return float(n)
    return None


def load_cost_table(path: Path | None = None) -> dict[str, float]:
    """Load op -> mean_us mapping from profiling JSON."""
    path = path or _DEFAULT_COST_TABLE
    if not path.exists():
        return {}
    with open(path) as f:
        raw = json.load(f)
    return {op: entry["mean_us"] for op, entry in raw.items()}


class CostModel:
    """FLOPs-based cost model with profiled-latency fallback.

    Prefers FLOPs estimate when shape information is available.
    Falls back to per-op average latency from ORT profiling.
    All ops are legal — no supported-op filtering.
    """

    def __init__(self, cost_table: dict[str, float] | None = None) -> None:
        if cost_table is None:
            cost_table = load_cost_table()
        self._table = cost_table
        if cost_table:
            values = sorted(cost_table.values())
            self._default = values[len(values) // 2]
        else:
            self._default = 10.0

    def node_cost(
        self,
        enode: ENode,
        output_shape: tuple[int, ...] | None = None,
        input_shapes: list[tuple[int, ...] | None] | None = None,
    ) -> float:
        if enode.op in _FREE_OPS:
            return 0.0

        flops = estimate_flops(enode.op, output_shape, input_shapes, enode.attrs)
        if flops is not None:
            # Scale FLOPs to microseconds-like range so it's comparable
            # with the profiled fallback.  1 GFLOP ≈ 1000 us on a modern
            # single-core CPU (~1 GFLOPS for non-SIMD scalar work, but
            # BLAS kernels are much faster).  We use a rough 1 MFLOP = 1 us.
            return flops / 1e6

        # Fallback: profiled op-type average.
        return self._table.get(enode.op, self._default)

    def is_legal(self, enode: ENode) -> bool:
        """All ops are legal — we optimize purely for latency."""
        return True
