"""Cost model for e-graph extraction.

Uses profiled per-op latency from ONNX Runtime to guide extraction
toward lower-latency programs.
"""

from __future__ import annotations

import json
from pathlib import Path

from ..egraph.enode import ENode
from ..ir.node import OP_INPUT, OP_NOOP, OP_PROJ, OP_WEIGHT

# Ops that are structural/boundary — zero cost.
_FREE_OPS = frozenset({
    OP_INPUT, OP_WEIGHT, OP_NOOP, OP_PROJ,
    "Constant", "ConstantOfShape",
})

# Default cost table path (generated by profile_ops.py).
_DEFAULT_COST_TABLE = Path(__file__).resolve().parent.parent.parent.parent / (
    "artifacts/superopt/op_cost_table.json"
)


def load_cost_table(path: Path | None = None) -> dict[str, float]:
    """Load op -> mean_us mapping from profiling JSON."""
    path = path or _DEFAULT_COST_TABLE
    if not path.exists():
        return {}
    with open(path) as f:
        raw = json.load(f)
    return {op: entry["mean_us"] for op, entry in raw.items()}


class CostModel:
    """Profiled latency cost model.

    Uses per-op mean execution time (microseconds) from ORT profiling.
    Ops not in the cost table get a default cost (median of known ops).
    All ops are legal — no supported-op filtering.
    """

    def __init__(self, cost_table: dict[str, float] | None = None) -> None:
        if cost_table is None:
            cost_table = load_cost_table()
        self._table = cost_table
        # Default cost for unknown ops: median of known costs, or 10.0 fallback.
        if cost_table:
            values = sorted(cost_table.values())
            self._default = values[len(values) // 2]
        else:
            self._default = 10.0

    def node_cost(self, enode: ENode) -> float:
        if enode.op in _FREE_OPS:
            return 0.0
        return self._table.get(enode.op, self._default)

    def is_legal(self, enode: ENode) -> bool:
        """All ops are legal — we optimize purely for latency."""
        return True
