"""Shared operator contracts for ONNX rewrite and future superopt stages."""

from __future__ import annotations

BENCHMARK_ONNX_OPSET = 17
BENCHMARK_ONNX_MIN_OPSET = 13

VISION_SUPPORTED_OPS: frozenset[str] = frozenset(
    {
        "Add",
        "AveragePool",
        "Cast",
        "Clip",
        "Concat",
        "Conv",
        "Div",
        "Erf",
        "GatherElements",
        "Gelu",
        "GlobalAveragePool",
        "HardSigmoid",
        "HardSwish",
        "LeakyRelu",
        "MatMul",
        "MaxPool",
        "Mul",
        "ReduceMax",
        "ReduceMean",
        "Relu",
        "Reshape",
        "Resize",
        "Sigmoid",
        "Slice",
        "Softmax",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Tile",
        "TopK",
        "Transpose",
    }
)

LLM_SUPPORTED_OPS: frozenset[str] = frozenset(
    {
        "Abs",
        "Add",
        "And",
        "ArgMax",
        "ArgMin",
        "Asin",
        "Atan",
        "AveragePool",
        "BatchNormalization",
        "Cast",
        "Ceil",
        "Clip",
        "Concat",
        "Conv",
        "ConvTranspose",
        "Cos",
        "CumSum",
        "DepthToSpace",
        "DequantizeLinear",
        "Div",
        "Einsum",
        "Elu",
        "Equal",
        "Exp",
        "Erf",
        "Expand",
        "Flatten",
        "Floor",
        "Gather",
        "GatherElements",
        "GatherND",
        "Gelu",
        "Gemm",
        "GlobalAveragePool",
        "GlobalMaxPool",
        "Greater",
        "GreaterOrEqual",
        "GridSample",
        "HardSigmoid",
        "HardSwish",
        "InstanceNormalization",
        "Inverse",
        "LRN",
        "LSTM",
        "LayerNormalization",
        "LeakyRelu",
        "Less",
        "LessOrEqual",
        "Log",
        "LogSoftmax",
        "LpNormalization",
        "MatMul",
        "Max",
        "MaxPool",
        "Mean",
        "Min",
        "Mod",
        "Mul",
        "Neg",
        "Not",
        "Or",
        "PRelu",
        "Pad",
        "Pow",
        "QuantizeLinear",
        "RandomUniformLike",
        "Reciprocal",
        "ReduceL2",
        "ReduceMax",
        "ReduceMean",
        "ReduceMin",
        "ReduceProd",
        "ReduceSum",
        "Relu",
        "Reshape",
        "Resize",
        "Round",
        "STFT",
        "ScatterElements",
        "ScatterND",
        "Sigmoid",
        "Sign",
        "Sin",
        "Slice",
        "Softmax",
        "SpaceToDepth",
        "Split",
        "Sqrt",
        "Squeeze",
        "Sub",
        "Sum",
        "Tanh",
        "ThresholdedRelu",
        "Tile",
        "TopK",
        "Transpose",
        "Unsqueeze",
        "Upsample",
        "Where",
    }
)

VISION_OPS = VISION_SUPPORTED_OPS
LLM_OPS = LLM_SUPPORTED_OPS

UNION_SUPPORTED_OPS: frozenset[str] = frozenset(
    VISION_SUPPORTED_OPS
    | LLM_SUPPORTED_OPS
    | {
        "Clip",
        "Constant",
        "ConstantOfShape",
        "Cos",
        "Equal",
        "Erf",
        "Expand",
        "Flatten",
        "GatherElements",
        "Gelu",
        "IsNaN",
        "LeakyRelu",
        "Less",
        "LessOrEqual",
        "Max",
        "Min",
        "Mod",
        "Neg",
        "Pad",
        "Pow",
        "Range",
        "ReduceMax",
        "ReduceSum",
        "Shape",
        "Sin",
        "Tanh",
        "Tile",
        "TopK",
        "Unsqueeze",
        "Where",
    }
)

SUPPORTED_OPS: frozenset[str] = UNION_SUPPORTED_OPS

# Practical LLM contract reading:
# - META_OPS are shape/layout bookkeeping ops that real systems often try to
#   reduce aggressively, but may still tolerate in limited form.
# - MUST_REMOVE_OPS are the dynamic mask/cache ops we want to eliminate even
#   in a practical accelerator-style contract.
LLM_META_OPS: frozenset[str] = frozenset(
    {
        "Concat",
        "Gather",
        "Reshape",
        "Shape",
        "Squeeze",
        "Transpose",
        "Unsqueeze",
    }
)
